services:
  - type: web
    name: your-app-name
    env: php
    plan: free
    buildCommand: "composer install"
    startCommand: "php -S 0.0.0.0:10000 -t /var/www/html"
    envVars:
      - key: DB_HOST
        value: your_database_host
      - key: DB_PORT
        value: "5432"
      - key: DB_NAME
        value: your_database_name
      - key: DB_USER
        value: your_database_user
      - key: DB_PASS
        value: your_database_password
